[2023-03-11T09:10:25.906+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snf_dag2.create_orders_table manual__2023-03-11T09:10:20.820134+00:00 [queued]>
[2023-03-11T09:10:25.912+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snf_dag2.create_orders_table manual__2023-03-11T09:10:20.820134+00:00 [queued]>
[2023-03-11T09:10:25.913+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T09:10:25.913+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-11T09:10:25.914+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T09:10:25.923+0000] {taskinstance.py:1300} INFO - Executing <Task(SnowflakeOperator): create_orders_table> on 2023-03-11 09:10:20.820134+00:00
[2023-03-11T09:10:25.928+0000] {standard_task_runner.py:55} INFO - Started process 497 to run task
[2023-03-11T09:10:25.931+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'snf_dag2', 'create_orders_table', 'manual__2023-03-11T09:10:20.820134+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/snf_dag_2.py', '--cfg-path', '/tmp/tmpmy6mkavw']
[2023-03-11T09:10:25.932+0000] {standard_task_runner.py:83} INFO - Job 62: Subtask create_orders_table
[2023-03-11T09:10:25.986+0000] {task_command.py:388} INFO - Running <TaskInstance: snf_dag2.create_orders_table manual__2023-03-11T09:10:20.820134+00:00 [running]> on host a2514c64f69a
[2023-03-11T09:10:26.036+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=snf_dag2
AIRFLOW_CTX_TASK_ID=create_orders_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-11T09:10:20.820134+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-11T09:10:20.820134+00:00
[2023-03-11T09:10:26.037+0000] {sql.py:254} INFO - Executing: create or replace table orders
as select * from "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."ORDERS" limit 1000;
[2023-03-11T09:10:26.044+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-03-11T09:10:26.491+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  "pyarrow", installed_pyarrow_version, pandas_pyarrow_extra

[2023-03-11T09:10:26.701+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-03-11T09:10:26.703+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.1, Python Version: 3.7.16, Platform: Linux-5.15.49-linuxkit-aarch64-with-debian-11.6
[2023-03-11T09:10:26.704+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-03-11T09:10:26.704+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2023-03-11T09:10:27.319+0000] {cursor.py:738} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-03-11T09:10:27.428+0000] {cursor.py:751} INFO - query execution done
[2023-03-11T09:10:27.430+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-11T09:10:27.432+0000] {sql.py:375} INFO - Running statement: create or replace table orders
as select * from "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."ORDERS" limit 1000;, parameters: None
[2023-03-11T09:10:27.433+0000] {cursor.py:738} INFO - query: [create or replace table orders as select * from "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF...]
[2023-03-11T09:10:28.701+0000] {cursor.py:751} INFO - query execution done
[2023-03-11T09:10:28.706+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-11T09:10:28.708+0000] {sql.py:384} INFO - Rows affected: 1
[2023-03-11T09:10:28.711+0000] {snowflake.py:391} INFO - Rows affected: 1
[2023-03-11T09:10:28.716+0000] {snowflake.py:392} INFO - Snowflake query id: 01aadf06-0000-4f6a-0004-9dfe0001513e
[2023-03-11T09:10:28.718+0000] {cursor.py:738} INFO - query: [COMMIT]
[2023-03-11T09:10:28.823+0000] {cursor.py:751} INFO - query execution done
[2023-03-11T09:10:28.824+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-11T09:10:28.824+0000] {connection.py:586} INFO - closed
[2023-03-11T09:10:29.087+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2023-03-11T09:10:29.249+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=snf_dag2, task_id=create_orders_table, execution_date=20230311T091020, start_date=20230311T091025, end_date=20230311T091029
[2023-03-11T09:10:29.313+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-11T09:10:29.327+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
