[2023-03-11T08:09:30.710+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snf_dag.load_emp_table manual__2023-03-11T08:09:25.234380+00:00 [queued]>
[2023-03-11T08:09:30.717+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snf_dag.load_emp_table manual__2023-03-11T08:09:25.234380+00:00 [queued]>
[2023-03-11T08:09:30.718+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T08:09:30.718+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-11T08:09:30.718+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T08:09:30.727+0000] {taskinstance.py:1300} INFO - Executing <Task(SnowflakeOperator): load_emp_table> on 2023-03-11 08:09:25.234380+00:00
[2023-03-11T08:09:30.732+0000] {standard_task_runner.py:55} INFO - Started process 883 to run task
[2023-03-11T08:09:30.735+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'snf_dag', 'load_emp_table', 'manual__2023-03-11T08:09:25.234380+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/snf_dag.py', '--cfg-path', '/tmp/tmp6edtxixa']
[2023-03-11T08:09:30.736+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask load_emp_table
[2023-03-11T08:09:30.794+0000] {task_command.py:388} INFO - Running <TaskInstance: snf_dag.load_emp_table manual__2023-03-11T08:09:25.234380+00:00 [running]> on host 1e740946fd0d
[2023-03-11T08:09:30.844+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=snf_dag
AIRFLOW_CTX_TASK_ID=load_emp_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-11T08:09:25.234380+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-11T08:09:25.234380+00:00
[2023-03-11T08:09:30.845+0000] {sql.py:254} INFO - Executing: insert into employees values
    (1, 'Vimal', 101, 'Sr Director', 200000, 'Delhi'),
    (2, 'Jeff Dean', 102, 'Vice President', 250000, 'New York'),
    (3, 'Arjun', 103, 'Sr Vice President', 300000, 'London'),
    (4, 'Raghavan', 103, 'Data Architect', 200000, 'Bangalore'),
    (5, 'Paul G', 103, 'Enterprise Architect', 200000, 'California');
[2023-03-11T08:09:30.853+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-03-11T08:09:31.251+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  "pyarrow", installed_pyarrow_version, pandas_pyarrow_extra

[2023-03-11T08:09:31.543+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-03-11T08:09:31.545+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.1, Python Version: 3.7.16, Platform: Linux-5.15.49-linuxkit-aarch64-with-debian-11.6
[2023-03-11T08:09:31.546+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-03-11T08:09:31.546+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2023-03-11T08:09:32.043+0000] {cursor.py:738} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-03-11T08:09:32.139+0000] {cursor.py:751} INFO - query execution done
[2023-03-11T08:09:32.140+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-11T08:09:32.142+0000] {sql.py:375} INFO - Running statement: insert into employees values
    (1, 'Vimal', 101, 'Sr Director', 200000, 'Delhi'),
    (2, 'Jeff Dean', 102, 'Vice President', 250000, 'New York'),
    (3, 'Arjun', 103, 'Sr Vice President', 300000, 'London'),
    (4, 'Raghavan', 103, 'Data Architect', 200000, 'Bangalore'),
    (5, 'Paul G', 103, 'Enterprise Architect', 200000, 'California');, parameters: None
[2023-03-11T08:09:32.143+0000] {cursor.py:738} INFO - query: [insert into employees values (1, 'Vimal', 101, 'Sr Director', 200000, 'Delhi'), ...]
[2023-03-11T08:09:32.336+0000] {cursor.py:751} INFO - query execution done
[2023-03-11T08:09:32.347+0000] {connection.py:586} INFO - closed
[2023-03-11T08:09:32.386+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2023-03-11T08:09:32.484+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 379, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 839, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 294, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 231, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 100078 (22000): 01aadec9-0000-4fdc-0004-9dfe0001607a: String 'Sr Director' is too long and would be truncated
[2023-03-11T08:09:32.517+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=snf_dag, task_id=load_emp_table, execution_date=20230311T080925, start_date=20230311T080930, end_date=20230311T080932
[2023-03-11T08:09:32.538+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task load_emp_table (100078 (22000): 01aadec9-0000-4fdc-0004-9dfe0001607a: String 'Sr Director' is too long and would be truncated; 883)
[2023-03-11T08:09:32.590+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-11T08:09:32.611+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
